#ifndef RKSEARCHLIBRARY_GLOBAL_H
#define RKSEARCHLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RKSEARCHLIBRARY_LIBRARY)
#  define RKSEARCHLIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RKSEARCHLIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RKSEARCHLIBRARY_GLOBAL_H
